name: test notebook

on: [push]

jobs:
  test-notebook:
    name: test Notebook
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: conda-incubator/setup-miniconda@v2
          
      - name: Install dependencies
        run: |
          conda env create -f environment.yml
          
      - name: execute all cells in notebook
        run: |
          conda activate anaconda_notebook
          jupyter nbconvert --to notebook --execute ipynb/Advent_of_Code_2021.ipynb --inplace
         
